### ISSUE TITLE
Delete NodeCache object itself

### ISSUE THREAD

**Issue by suiluj** [mpneuried/nodecache#116]
I am not sure if the node-cache object itself is completely deleted by the garbage collector when there is no reference to it left. Are there remaining things in the memory or does it keep internal `checkperiod`-events?

I have an object which contains multiple node-cache objects. The node-cache objects are added or removed dynamically.
The code example is simplified.

My questions:
Is there something left of the node-cache object when i delete it from my `trackedDeviceCaches` object.
I create the node-cache object in a function. So when my understanding is right it only is referenced in my `trackedDeviceCaches` object. Then at the end i delete the reference in the `trackedDeviceCaches` object and the garbage collector will completely delete the node-cache object.

Simplified code example:
```
const NodeCache = require( "node-cache" );

// contains 
let trackedDeviceCaches = {};

function createCacheForDevice(deviceName) {
    const newCacheForDevice = new NodeCache({ stdTTL: 20, checkperiod: 5 });
    trackedDeviceCaches[deviceName] = newCacheForDevice;
}


createCacheForDevice('device_one');
createCacheForDevice('device_two');

//i delete the last node-cache object reference
delete trackedDeviceCaches['device_one'];
```

My fear is that i would have a lot of node-cache object which take up memory and check for expiring keys even when i do not use them anymore. I know this is more of a general Node.js question but i am confused because of the "special" node-cache object.

**Comment by benny-medflyt** [comment]
I believe you must call `trackedDeviceCaches['device_one'].close()` before the last line (`delete`).

This is because the NodeCache installs a `setInterval` when it is created, which will have a closure that has a references to the NodeCache. So as long as this `setInterval` is running, the NodeCache will not be able to be garbage collected (because installed `setInterval` closures are considered as GC roots). When you call `close()` then the `setInterval` is uninstalled, and then the NodeCache will be eligible for garbage collection

**Comment by erdii** [comment]
Closed due to inactivity.
