### ISSUE TITLE
Saving the cache

### ISSUE THREAD

**Issue by Petah** [mpneuried/nodecache#34]
Any way to save to cache to the file system? or memcache/some kind of db?

**Comment by smrchy** [comment]
Nice idea for a new project that implements nodecache and does just this.

**Comment by tcs-de** [comment]
I'm developing a solution for this requirement during my time in the train.

Have a look: https://github.com/mpneuried/node-cache-persist
It's not published yet, because the documentation is missing and the api is not fixed yet.

**Comment by mpneuried** [comment]
I'm developing a solution for this requirement during my time in the train.

Have a look: https://github.com/mpneuried/node-cache-persist
It's not published yet, because the documentation is missing and the api is not fixed yet.

**Comment by cinder92** [comment]
and where is saving cache this project now?

**Comment by supukarmin** [comment]
Had the same problem, just wrote some short functions; no need for a library, the combination of .keys and .mget creates the magic:

```
const NodeCache = require('node-cache');
const fs = require('fs');
const path = require('path');

const cache = new NodeCache();

const saveCache = (cache, directoryPath = __dirname) => {
    cache.keys((err, keys) => {
      if (!err) {
        cache.mget(keys, (err, cacheData) => {
          if (!err) {
            const stringifiedData = JSON.stringify(cacheData);
            fs.writeFileSync(path.join(directoryPath, 'cache.json'), stringifiedData)
          } else {
            console.error(err);
          }
        });
      } else {
        console.error(err);
      }
    });
}

const loadCache = (cache, directoryPath = __dirname) => {
  const filePath = path.join(directoryPath, 'cache.json');
  if (fs.existsSync(filePath)) {
    const jsonData = fs.readFileSync(filePath, 'utf8');
    const data = JSON.parse(jsonData);
    for (const [key, val] of Object.entries(data)) {
      if (data.hasOwnProperty(key)) {
        cache.set(key, val);
      }
    }
  }
};

loadCache(cache);

//and then put it into an interval or save it after every change or whatever suits your needs

setInterval(() => {
  saveCache(cache);
}, 60*1000);

```

**Comment by erdii** [comment]
`fs.writeFileSync(path.join(directoryPath, 'cache.json'), stringifiedData)`

This will block your proccess while saving. I think you are better off with [fs.writeFile](https://nodejs.org/api/fs.html#fs_fs_writefile_file_data_options_callback)

Actually all fs.*Sync functions you use, have counterparts without the Sync-suffix, that will not block your process and use the callblack-pattern for the flow of your node-app.

**Comment by supukarmin** [comment]
@erdii No, it won't always block the process; it does that only if you put it into the wrong place or without making it prior async. So, it depends on your integration, I'm personally using it inside an interval (as in the example), which is non-blocking. It's one of these common misconception inside the JS community that always everything must be async, there is no need to force it always everywhere. It often creates unnecessary additional complexity which just leads to more complex bugs. Give the control over it to the integrator.

However, it may be useful for others to prevent bad integrations, so it's for sure noteworthy. I would even suggest to use the async keyword instead of passing down a callback + using the async .writeFile; this way you get easily to know when it finishes:

`const saveCache = async (cache, directoryPath = __dirname) => {`

**Comment by AnandChowdhary** [comment]
I made a library which uses a file system-based key-JSON storage, based on nodecache. It's kind of the opposite of "save the cache", since the primary source is the file system, but every key which is fetched is then saved in the cache. If you're still interested in having a file system store for your cache, check it out: https://github.com/AnandChowdhary/fraud/.

**Comment by erdii** [comment]
@AnandChowdhary Fraud looks like a nice project! Glad to see that you built something useful for you business on nodecache!

**Comment by erdii** [comment]
Closed because the filesystem is out of scope (at least for now)
