### ISSUE TITLE
get exact vsize

### ISSUE THREAD

**Issue by neophob** [mpneuried/nodecache#36]
Hi thanks for your lib, very usefull. however there is a small issue, I put elements in my cache that look like this:

```
var element = { buffer: aNodeBufferObject, contentType : 'image/png' };
```

the vsize for this type does not match, as it just don't know the type. maybe it would make sense to add an optional key into the element that specify the exact size? another idea would be to define a function that returns the exact size of an element.

what do you think?

**Comment by mpneuried** [comment]
Hi, within JS it's not simple to get the real memory size of a variable.
So nodecache tries to calc the size as simple as possibele.
See: https://github.com/tcs-de/nodecache/blob/master/_src/lib/node_cache.coffee#L437

In your case you are putting an object, witch leads to the code:
```js
this.options.objectValueSize * _.size( value ) // Values: 80 * 2 -> 160
```

I don't want to add code or another module for a better size calculation, because this will decrease the performance for every user, just to have better stats.
I hope you will agree with this.

But i could add an option where you can define a function to calculate the size your own or pass it to a module like [sizeof](https://www.npmjs.com/package/sizeof).

Example:
```js
var sizeof = require( "sizeof" )
var myCache = new NodeCache({
  fnVSize: sizeof.sizeof
});
```

**Comment by erdii** [comment]
Closed due to inactivity.
