### ISSUE TITLE
Why does a no-key-found delete increments stats' misses

### ISSUE THREAD

**Issue by DiegoRBaquero** [mpneuried/nodecache#55]
Hi,

I'm wondering as to why a delete miss would be a cache miss.

Here: https://github.com/tcs-de/nodecache/blob/master/_src/lib/node_cache.coffee#L223

Thank you

**Comment by mpneuried** [comment]
Good point ...

On the one hand i would count a delete miss, because it's a valid request to the cache.
But on the other hand it should also count a delete of an existing key as hit ...

Memcached, for example, counts every hit and miss for each command.

```
...
STAT cmd_get 2
STAT cmd_set 1
STAT cmd_flush 0
STAT cmd_touch 0
STAT get_hits 0
STAT get_misses 2
STAT delete_misses 1
STAT delete_hits 0
STAT incr_misses 0
STAT incr_hits 0
STAT decr_misses 0
STAT decr_hits 0
STAT cas_misses 0
STAT cas_hits 0
STAT cas_badval 0
STAT touch_hits 0
STAT touch_misses 0
...
```

So there are three solutions:
- don't count a delete miss
- also count a delete hit
- far more detailed stats similar to memcached

Whats your opinion?

**Comment by DiegoRBaquero** [comment]
I definitely think it should be more detailed or not count it (if it's too much trouble)

The notion of a 'hit/miss' in a cache is when you go search it. I feel that the way it is affects the statistic.
