### ISSUE TITLE
useClones question

### ISSUE THREAD

**Issue by lmessinger** [mpneuried/nodecache#83]
In the document it says: 
Note: true is recommended, because it'll behave like a server-based caching. 

could anyone explains that? what does it mean "behave like a server-based caching." ?

**Comment by mpneuried** [comment]
hi,

you should normaly use `useClones: true` because this will save the given data by cloning it.
So for example if you cache a object value `X` to the keys `A` and `B` and then change the value in `A`, `B` will still have the original value _( as you would expect in a server based cache like memchached, redis, ... )_
If you set `useClones: false` node-cache will cache the raw value. For complex data like objects it now will only cache the value reference.

Here'a an example:
https://runkit.com/mpneuried/useclones-example-83

Please let me know if this answers your question

**Comment by simllll** [comment]
What do you think about "Object.freeze()" instead of cloning the object? Wouldn't this save some memory and will have the same result? Just stumpled over it due to some weird behaviour in our app and found out it was indeed related with useClones: false, .. now I'm looking over some more memory efficient way instead of cloning and can't see why Object.freeze shoudl not work? Thanks for any hints and advices :)

**Comment by erdii** [comment]
Nice idea, but this won't work because you can not alter an object after you cached it.
Say, you cache an object `user` and want to change his name afterwards.
This would definitely break some downstream applications.

**Comment by simllll** [comment]
I'm still playing around with it. You are right, the behaviour is indeed somehow different. Maybe we find another option, e.g. "useFreeze: true/false" or objectMode: "clone", "freeze", "none".
In my tests changing freezing objects does not run into any exceptions (guess this is related to the node version or strict mode), but somehow I'm still experiecing issues with "freeze". Objects loses some data over time, even though it is "frozen". Need to look further into this.

**Comment by erdii** [comment]
yeah. changing properties after freezing the object only throws in strict mode.

if you really want the freeze behaviour, you could write a wrapper function for a cache with `useClones: false` that freezes the object before caching it.

example:

```JAVASCRIPT
const myCache = new NodeCache({ useClones: false });
myCache.setFrozen = function(key, value, options) {
  Object.freeze(value);
  this.set(key, value, options);
}
```

but your object has to be in FINAL state before you cache it because, as already said, you can't modify it afterwards

**Comment by simllll** [comment]
Thanks for your hints,
what I ended up now is following code:

```
// recursivily freeze object
const myCache = new NodeCache({ useClones: false });

function deepFreeze(obj,propName) {

    // Retrieve the property names defined on obj
    var propNames = Object.getOwnPropertyNames(obj);

    // Freeze properties before freezing self
    propNames.forEach(function(name) {
        var prop = obj[name];

        // Freeze prop if it is an object
        if (typeof prop == 'object' && prop !== null)
            deepFreeze(prop,name);
    });

    // Freeze self (no-op if already frozen)e
    try {
        if(obj instanceof Buffer) obj = obj.toString('hex');
        return Object.freeze(obj);
    }catch(e) {
        console.log("was not able to freeze",typeof obj, propName, obj, obj.toString('hex'));
        return obj;
    }
}

```

and setting it then just by calling:
`myCache.set("key", deepFreeze(obj));
`

just in case someone can use it ;)

simon
